---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: golangvzla
  region: us-east-1
  version: "1.25"
availabilityZones:
- us-east-1a
- us-east-1b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.medium
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20